name: Android

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  debug:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода
        uses: actions/checkout@v6

      - name: Настройка Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Загрузка libvkturn.so
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          curl -fL \
            https://github.com/cacggghp/vk-turn-proxy/releases/latest/download/client-android-arm64 \
            -o app/src/main/jniLibs/arm64-v8a/libvkturn.so

      - name: Сборка debug APK
        run: sh gradlew assembleDebug

      - name: Загрузка debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
